### ISSUE TITLE
Dominos_Cast

### ISSUE THREAD

**Issue by Goranaws** [tullamods/Dominos#186]
I am planning to overhaul the cast bar soon. I have a few new ideas I would like to try out. I hope to have a testable version for you soon(ish)

**Comment by ckaotik** [comment]
An update to the castbar would be glorious! Some ideas, if you need any (sorted by "personal importance rating", descending) ;)
- latency overlay
- simple icon (outer/inner left)
- total cast time (additionally to the already displayed time left)
- enable/disable components
- component positioning, e.g. icon, cast time etc.

Yes, there are already many castbar addons out there, so I totally understand if no extra features are added. Can't hurt to ask though ;)

**Comment by Tuller** [comment]
I think there should be a latency overlay, icon, and probably shared media support.  My preferred look is that of the primary screenshot of [AzCastBar] (http://www.wowinterface.com/downloads/info7458).  

But yes, I definitely prefer to skew towards simple features on the bar due to the fact that its an optional addon for Dominos and that there are many more of them out there :)

**Comment by Goranaws** [comment]
Just posting this here for anyone interested. :)
I have been working on this and a testable version is available here: https://github.com/tullamods/Dominos_Cast
I would like to have several people test the latest version before I continue. I've have completely rewritten  https://github.com/tullamods/Dominos_Cast/blob/master/castBar.lua from scratch and would really like some feedback.. Lots of new stuffs!!

**Comment by Guema** [comment]
> latency overlay
Very important feature for casters, helps to anticipate movement between casts.

I'll suggest to add a customisable border too. but it is a detail.

**Comment by Tuller** [comment]
![latency](https://cloud.githubusercontent.com/assets/191239/18028780/dc3d8ba2-6c54-11e6-8fba-3d5b6c60e785.png)

Like this?

**Comment by Guema** [comment]
Hum. This is a possible way. Not my favourite throught. let me explain why : 

When casting, you want to know what is latency because when your spell hit the latency margin of error, your spell is considered success. Considering that i would opt for something like this :

![latency](https://cloud.githubusercontent.com/assets/8943532/18030748/8a4a0252-6cc3-11e6-9b03-6ab2aee8bc11.png)
 
In this version latency doesn't move with cast bar, and keep to the end, that let you anticipate castbar hitting the latency easier.

______________________________

Saying that, what i notice is very off topic, but, i tested in game with very few latency. this few latency made the cast bar to seem to have a "flash" effect at the end (the end of the bar was more bright). Ergonomycally, it is very interesting, because human brain is optimized to see easily bright things moving, even in peripheral vision.

Sounds like nothing, but it can helps player to focus on other thing, keeping an eye on there castbar, easier with a flash like this. So i suggest to let some pixels bright at the ends for this.

**Comment by Tuller** [comment]
Having a static latency area is probably the best approach. The reason I've tried this one first is actually intended to provide somethings like a flash effect at the same time

**Comment by Guema** [comment]
Yeah i see.

I think a flash is un interesting idea too.
You are going to set a constant sized (or based on castbar size) flash effect and a static latency bar, i suppose ?

**Comment by Tuller** [comment]
![ds 2](https://cloud.githubusercontent.com/assets/191239/18036636/7d008adc-6d3e-11e6-8534-a0286903563d.png)
![ds 3](https://cloud.githubusercontent.com/assets/191239/18036650/b5e1b8f8-6d3e-11e6-86fe-577f4758116a.png)

What I'm playing around with is a gradient effect instead of a spark right at the end.

**Comment by Guema** [comment]
Tested last build.

Very solid build. the gradient is beatiful and very effective fine for peripherial vision trick. Latency and border too.
__________
Latency is well good, a detail could be to limit the displaying latency to the bar width, because sometime, it runs out of it. Not mandatory or urgent trough.
__________
Chose Border Skin and Size (SharedMedia), Font Size, and total time should be awesome nexts steps !
__________
Those are Feedbacks and suggestions, hope this can help ^^.

**Comment by ckaotik** [comment]
Wow, this has turned out really beautifully. Great work! How do you decide on the colors of the main and latency progress?

This is probably an idea that doesn't quite fit with the scope of an action bar replacement addon ... but could we also do the target's cast bar?

**Comment by Tuller** [comment]
The green, purple, and yellow base colors are taken from when I implemented them as help/harm/neutral spell indicators.  The latency zone colors are [complementary colors](https://en.wikipedia.org/wiki/Complementary_colors) of those.

If you change main.lua from
```
function CastBarModule:Load()
  self.frame = Addon.CastBar:New('cast', 'player')
end
```
to
```
function CastBarModule:Load()
  self.frames = {
    Addon.CastBar:New('cast', 'player'),
    Addon.CastBar:new('ctarget', 'target') 
  }
end
```
You _should_ end up with a target cast bar.

**Comment by ckaotik** [comment]
That works nicely, thanks! 👍 

There's one other thing I'm unsure of: Does the castbar display the "shield" icon for spells that cannot be interrupted? Alternatively, use a gray cast bar color, but that might already be used for some damage type?

**Comment by Tuller** [comment]
I don't currently implement a display for non interruptible spells.  I wasn't sure how useful it would be for just player cast spells
