### ISSUE TITLE
default bar paging

### ISSUE THREAD

**Issue by Goranaws** [tullamods/Dominos#308]
This has been  bugging me for some time.. Since all bars a visible by default, we should either remove all default paging, or hide the bars that are set as defaults for paging. 

I have noticed the "my bars are duplicated" issue comes up quite a bit, so thinking something has got to give.

**Comment by Tuller** [comment]
I’m working on another project for a client which is why I’ve not had much movement here, but the general idea is that I’m going to do a new version of DominosDB with better defaults. The first target will be a layout that mirrors the new one in battle for Azeroth.

I’ll need to deprecate the 1-120 bars option to do this, but configuration would allow enabling/disabling individual bars from the /dominos menu.

**Comment by Tuller** [comment]
Blizzard opted to remove the bindings by default, so problem solved :)
