### ISSUE TITLE
"Cancel button" for things like karazhan chess event gone

### ISSUE THREAD

**Issue by mattiaseri** [tullamods/Dominos#503]
Hello!

Tried running Karazhan yesterday, first time since installing the Dominos addon, but found some problems when entering the Chess Event. The "Cancel button" (don't know what it's called) which in the Blizzard UI is positioned above the default actionbar was gone. Tried to enable all parts of Dominos but had to reload without the addon for the button  to reappear. 

**Addon Version**
9.0.13-Retail

**World of Warcraft Version**
Retail

**Comment by addonaddict** [comment]
this could be due to removal of a bar such as the one that pops up when using Eye of Killrog (warlock ability)
perhaps a better option would be to turn it into its own bar just like all the other action bars and let the user control where it goes
outright removing it is not ideal as it removes basic functionality instead of improving it

**Comment by Tuller** [comment]
This is implemented in the latest version
