### ISSUE TITLE
config mode: baseline and cancel changes

### ISSUE THREAD

**Issue by Swanarog** [tullamods/Dominos#516]
I've begun working on this concept, but can't seem to make the final part work. I have the code in place, but can't get anything update visually, until after a reload. https://github.com/Swanarog/Dominos/blob/master/Dominos_Config/overlay/help.lua

Baseline: User presses button to take snapshot of current settings for all frames in current profile. Then, if the user makes undesired changes, they can click the same button to revert back the baseline settings. stored baseline is stored between config mode toggles... try a layout, play with it for a while, then revert to baseline if you don't like it. not stored between reloads

Cancel Changes: Revert current settings of all frames to state before config mode was most recently activated.

I'm hoping you might like this idea enough to look into it.

**Comment by Tuller** [comment]
Snapshotting is a good idea. We just have to make sure that when the user exists config mode, they really are exiting config mode with the intention of saving changes.

Some fun edge cases:
* I use /dom config to exit
* I enter combat (which hides config mode temporarily now)
* I hide my UI via alt+z or something

Also instead of a copy, it might be a bit safer to actually create a whole new profile (thing-snapshot-time) and then apply those settings if they hit save. That'll capture things beyond normal Dominos module load/unload events.

**Comment by Swanarog** [comment]
I do not currently have internet at home, won't till Thursday when we have
our internet service provider changed.

Maybe when config mode is canceled, it opens a pop-up asking if you want to
save changes. And if you ignore or pass up the message, it will
automatically save, But will retain the snapshot just in case.
