### ISSUE TITLE
(Question) Advanced show states for fading bars

### ISSUE THREAD

**Issue by addonaddict** [tullamods/Dominos#519]
Hello,

I am not very good with coding and just cant figure out how to make this work...
Any chance you could give me a code example of how to achieve the following criteria:

I want my action bar to:
Fade out automatically (i got this to work) fade out to 1%, fade in to 100% on following conditions:
**Fade in on mouseover** - not sure how
**Fade in when I have a target** - not sure how
**Fade in when casting** - not sure how
**Fade in when my health is less than 100%** - not sure how
**Fade in when my pet's health is less than 100%** - not sure how, (not as important)

![image](https://user-images.githubusercontent.com/73442541/101857451-85430700-3b35-11eb-9cce-82f9f08cd625.png)

ELVUI action bars do all this by default but I have no clue how to properly code this into Dominos... so your help would be greatly appreciated
Thank you :) awaiting your reply!

**Comment by Tuller** [comment]
**Mouse-over fading:**
This is done via the fading panel (eventually to be renamed Visibility). Fade in controls the normal opacity of the bar. Fade out controls the opacity when the bar isn't moused over.

**Show states:**
Show states accepts a [macro conditional](https://wow.gamepedia.com/Macro_conditionals) followed by one of three options:
* __show__ - Show the bar, and display at normal opacity level, taking into account mouse over settings.
* __hide__ - Hides the bar
* __\<number\>__ - Shows the bar at `<number>`% opacity. 100 is fully opaque, 0 is fully transparent

So for example
```lua
[combat][mod]100;[@target,exists]show;hide
```

This will set the bar to be show at 100% opacity in combat or if you're holding down a modifier key, show if you have a target, and hide otherwise. 

So going back to your list:
* Fade in on mouseover - Adjust the fade in slider for what your want your bar to be when moused over, and the fade out slider to what you want to be when the bar isn't moused over.
* Fade in when I have a target - `[@target,exists]show` or `[@target,exists]100` to show the bar and force it to be at 100% opacity.
* Fade in when casting - Not possible. You can try `[channeling]show` for spells you're channeling
* Fade in when my health is less than 100% - Not possible.
* Fade in when my pet's health is less than 100% - Not possible.

The not possible ones are because the show states option in Dominos is used to control bar visibility in addition to opacity levels. We're restricted in what conditions we can use to hide/show things in combat (pretty much anything you can write a macro for)

**Comment by addonaddict** [comment]
thank you!

**Comment by addonaddict** [comment]
Something is not working out when I tried your code:
[combat][mod:shift]100;[@target,exists]show;hide

The code itself works for the bar, but because of this the *mouseover* function no longer works for the bar that has this advanced state

this is especially difficult when i have enabled *docked bars inherit opacity* as this show state you gave me only works if i can input it onto the exact bar i want or it doesnt work - so if i have my expiernece bar clamped to action bars, even though it is docked to the action bar, it will not work the same

there is a bar on the screenshot below where the arrow is pointing, all other bars + exp bar is anchored to it.
in the image i am mousing over it but it doesnt show up even though it is properly setup in the *fading* options (image 2)
![image](https://user-images.githubusercontent.com/73442541/101988621-b4a66080-3c68-11eb-8103-545b2d4d1081.png)
![image](https://user-images.githubusercontent.com/73442541/101988647-e1f30e80-3c68-11eb-8e1a-514eb08ff62a.png)


I hope this explains what my problem is

**Comment by Tuller** [comment]
Can you provide the showstates panel too?

**Comment by addonaddict** [comment]
im out of the town for a few weeks so i dont have access to the game, but all other options are by default as they come with pre-installed dominos

**Comment by addonaddict** [comment]
I was able to hop onto a laptop and try it out. I managed to solve it with some luck...
I modified the macro in advanced show state to be:
[combat][mod:shift][@target,exists]100;

This seems to have allowed it to work while obeying the settings in "Fading" tab which allow mouseover fading

This solves all my questions :)

By the way - thank you so much for maintaining the addon and doing such a great job helping people out. Its rare to see someone getting things done so quick 👍 :)

**Comment by st4s1k** [comment]
**Show States:**
```lua
[exists]100;nil
```
**nil** - fallback to default mouse hover behavior
**Opacity:** 100
**Faded opacity:** 0
