### ISSUE TITLE
Enhanced grid display and snapping

### ISSUE THREAD

**Issue by Swanarog** [tullamods/Dominos#542]
The current implementation of the alignment grid feels very choppy when changing grid density. It also does not display the grid with a truly square grid. Individual squares on the grid are always rectangles. 

I've rewritten the code to correct both of those issues, and I'm going to include a short video of the grid density being changed to show how smooth the grid display appears now. If you like what you see, I'll make a fork and post it for you.

(video in next comment)

**Comment by Goranaws** [comment]
The video

**Comment by Goranaws** [comment]
Video

**Comment by Goranaws** [comment]
https://giphy.com/gifs/pWdYpbuIvPkW9Xw2uo

**Comment by Swanarog** [comment]
Proposed code changes:

https://github.com/tullamods/Dominos/compare/master...Swanarog:patch-2
https://github.com/Tuller/FlyPaper-2.0/compare/master...Swanarog:patch-1

**Comment by Swanarog** [comment]
I've updated my previous comment with a new link that includes all necessary code changes to go with the better grid display

**Comment by Tuller** [comment]
I've cherry picked the grid commits into the main branch and made a few adjustments. The main thing I've done differently is use GetScreenHeight as the factor for determining scale instead of width. That part is more consistent across various multi monitor and aspect ratios, I think. (I use a 21:9 monitor, for example).
