### ISSUE TITLE
Is there a modifier for cooldown?

### ISSUE THREAD

**Issue by Gundulf981** [tullamods/Dominos#551]
In your advanced section under show states you have variables for conditions like combat for opacity, i.e.

[combat]75;25

I'd like the icons for my spells / abilities that are on cooldown to more pronouncedly dim down, just to make it a little more clear when they kick back into the available column.  I tried 

[cooldown]show;25  and saw no change
[cooldown]25;show dimmed all the buttons on that bar

Is [cooldown] a variable?  Is there an alternate?  If no to both, can I toss it in the list.

Frankly, the mod is perfect as it is, I can't wow without it. Many thanks. Just figured I'd ask if it wasn't much trouble.

**Comment by Tuller** [comment]
Here’s the complete list of macro conditionals. Nothing cooldown related, unfortunately 
https://wow.gamepedia.com/Macro_conditionals

It’s something that could be implemented (step one, parse state: step two,  watch for cooldown on bar) but it wouldn’t work with the show/hide options due to restrictions on what Blizzard lets us do in combat. So you’d only be able to dim the bar.

**Comment by Gundulf981** [comment]
Thanks so much for the list! I will enjoy trying new combinations.  Cheers!
