### ISSUE TITLE
(REQUEST) add a "stagger" option for 2+ rows/columns

### ISSUE THREAD

**Issue by wmarler** [tullamods/Dominos#742]
Currently when an action bar has fewer columns than size, buttons are arranged in a straight grid. E.g. size 12, columns 6 you get 2 rows of buttons like this:

```
X X X X X X
X X X X X X
```

I like to stagger my rows of buttons, so that the rows of buttons visually mimics how a keyboard is laid out. Keys aren't in perfectly-aligned columns, they are staggered. E.g. this:

``` 
X X X X X X
 X X X X X X
```

I can do this using one action-bar per row, and I do. I typically only assign actions to the buttons 1-5, sometimes 1-6, because those are the buttons under my left hand. Then I page my bars so that I have different buttons with Alt, and Shift. This works well, but it leaves the buttons to the right of the bar unused. 

With the latest expansion I decided to roll a Druid and I'm finding that I don't have enough bars to page by Alt & Shift AND paging by cat/bear/druid form as I like. There aren't enough bars for all the paging permutations.

So I was wondering if there's a way to have the visual "stagger" effect that like built in to Dominos. When columns < size, instead of splitting the bar so the additional row/rows of buttons are directly below the previous row, allow them to be staggered by a configurable amount. Then a player could use 1 bar to make the 2 staggered rows, and use all the buttons.

If this is something you'd consider adding to Dominos, but don't have the cycles to code yourself, I could give a shot at it myself, and send you a pull request for. Trouble is, I'm totally unfamiliar with LUA in general and your code specifically. Would you point me in the right area of your code to modify?

Much obliged,

**Comment by catthou** [comment]
I'd love this; I actually just set up my main 3 action bars this way (hotkeys, ctrl-hotkeys, and shift-hotkeys for each bar respectively) but it'd be really nice if I could use a staggered layout it with just 1 or 2 hotbars (say, F1-F4 with ctrl and shift variants.).

The question I have is what would row 3 look like? Would it be inset further than row 2 or would it be asligned like row 1? In my head indenting each row would make more sense but on my hotbars I have row 1 and 3 aligned with each other and only row 2 inset, so that probably makes more sense?

**Comment by wmarler** [comment]
In my conceptualizing this, the "stagger" value would offset each row the same amount from the row above. So 3 rows (12-buttons on the action bar) would look like this:
`
X X X X
  X X X X
    X X X X`

4 rows like this:
`
X X X
  X X X
    X X X
      X X X
`

**Comment by Tuller** [comment]
![image](https://github.com/tullamods/Dominos/assets/191239/d6dffb8d-880d-4ff5-8417-86878cce478c)
